services:
    webserv:
        container_name: webserv
        build:
            context: .
            dockerfile: Dockerfile
        image:          webserv_img
        ports:
            - "8084:8084"
        networks:
            your_network:
                ipv4_address: 192.168.1.101

networks:
  your_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24