services:
    webserv:
        container_name: webserv
        build:
            context: .
            dockerfile: Dockerfile
        image:          webserv_img
        ports:
            - "8084:8084"
        